import { createSlice, nanoid } from "@reduxjs/toolkit";

//initialize state
const initialState = {
  todos: [{ id: 1, text: "Hello world" }],
};

//create slice
export const todoSlice = createSlice({
  name: "todo",
  initialState,
  reducers: {
    //contain property and fun
    addTodo: (state, action) => {
      const todo = {
        id: nanoid(),
        text: action.payload,
      };
      state.todos.push(todo);
    },
    /*
state: current state jo bhi hai
action: jobhi data pass hora hai
*/
    removeTodo: (state, action) => {
      state.todos = state.todos.filter((todo) => todo.id !== action.payload);
    },
    //update
    //delete
  },
});

/*it exports the action generated by the createSlice function.
Without exporting these action creators, you wouldn't be able to easily dispatch these actions from your React components or other parts of your application.
*/
export const { addTodo, removeTodo } = todoSlice.actions;

/*
export default todoSlice.reducer: Exports the reducer function, enabling you to include it in your Redux store configuration, so your application can manage the todos state.
*/
export default todoSlice.reducer;
